# Generated by Django 5.0.1 on 2024-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aoo1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emp",
            name="id",
        ),
        migrations.AlterField(
            model_name="emp",
            name="eno",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
