# Generated by Django 5.0.1 on 2024-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=20)),
                ("mob", models.IntegerField()),
                ("addrs", models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name="sample",
        ),
    ]
