# Generated by Django 5.0.1 on 2024-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="sample",
            fields=[
                ("sno", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
